FROM ghcr.io/ggml-org/llama.cpp:server

CMD [ \
  "-m", "/models/Qwen2.5-3B-Instruct-Q4_K_M.gguf", \
  "--host", "0.0.0.0", \
  "--port", "8080", \
  "-t", "4", \
  "-tb", "4", \
  "--flash-attn", "on", \
  "--cache-type-k", "q4_0", \
  "--cache-type-v", "q4_0", \
  "-c", "4096", \
  "--repeat-penalty", "1.15" \
]
